apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  projectID: mussia-infra
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
#      name: gcp-secret
      name: gcp-auth
      key: creds
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-secret
      key: creds

#      key: key-file
